name: Manual Deployment to EKS

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to deploy"
        required: true

env:
  ecr: 814254045460.dkr.ecr.ap-northeast-1.amazonaws.com
  image: task-6-1
  EKS_CLUSTER_NAME: task-6-1-eks
  ECR_REPOSITORY: task-6-1

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send workflow URL to Discord
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"content": "Webapp ${{ github.event.inputs.tag }} 準備部署到 Production! 請協助 Approve: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
  deploy:
    needs: notify-discord
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Update EKS Cluster config
        env:
          EKS_CLUSTER_NAME: ${{ env.EKS_CLUSTER_NAME }}
          AWS_REGION: ap-northeast-1
        run: |
          aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION
          echo "update eks config success"

      - name: Deploy to EKS
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.event.inputs.tag }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
        run: |
          sed -i.bak "s|DOCKER_IMAGE|$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|g" webapp/src/k8s/webapp.yaml && \
          kubectl apply -f webapp/src/k8s/webapp.yaml
          echo "deploy to eks success"
